
name: CI 
on:
  push:
    branches:
      - main

jobs:
    build:
      #  defaults:
        #  run:
          #  working-directory: ./terraform

       runs-on: ubuntu-latest

       env:
        Cloud: "Azure"

       steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: login to Azure
          uses: azure/login@v2
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            enable-AzPSSession: true 

        - name: Run Azure PowerShell inline script
          uses: azure/powershell@v2
          with:
           inlineScript: |
             Get-AzResourceGroup  
           azPSVersion: "latest"


        # - name: using variables
        #   run: echo "the name of my cloud is ${{env.Cloud}}"
      
        # - name: Sensitive data
        #   run: echo "get my password:${{secrets.FORTKNOX}}"

        # - name: Using repo variables
        #   run: echo "my name is:${{vars.secretname}}"

        # - name: open terraform folder
        #   run: ls ./terraform

