

name: CI 
on:
  push:
    branches:
      - main
env:
  ORG: "Coco"

jobs:
  build:
      # defaults:
      #   run:
      #     working-directory: ./terraform

      runs-on: ubuntu-latest

      env:
        Cloud: "Azure"
         

      steps:
        - name: using variables
          run: echo "the name of my cloud is ${{env.Cloud}}"
      
        - name: Sensitive data
          run: echo "get my password:${{secrets.FORTKNOX}}"